### ISSUE TITLE
Unable to enter an ESC character in OSX

### ISSUE THREAD

**Issue by davidmweber** [AWSXXF/vscode-serial-terminal#1]
I connect to a serial console just fine and I am able to interact with the shell at the remote end but I am unable to send an "ESC". So I cannot exit vi for example.

**Comment by littrick** [comment]
Hi，davi. I have tested that I can send `ESC` properly in the serial terminal. Also, I've found that sometimes I can't send `ESC` when interacting with vscode's built-in terminal. So yours should be a problem with vscode itself. You can fix it by pressing `F1` to search and run the `Reload Window` command.
