### ISSUE TITLE
Added the file transfer function of the x/y/z modem

### ISSUE THREAD

**Issue by mzq2306** [AWSXXF/vscode-serial-terminal#2]
I often need to transfer some small files through the serial port because it is very convenient. It is best to support two ways :
1. drag the file to the window to send the file; 
2. Enter the rz/sz command manually.

**Comment by littrick** [comment]
Nice suggestion, but I haven't used the x/y/z modem protocol to transfer files, maybe I'll research libraries to implement this later, or I'll implement the protocol
